modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="tutorialmod"
version="${file.jarVersion}"
displayName="Mod"
logoFile="examplemod.png"
credits="A mod by MattIce"
authors="MattIce"
description='''
A tutorial mod by MattIce.
'''

[[dependencies.tutorialmod]] 
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
